[package]
name = "role-server"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
axum = "0.8"
macroni = { path = "../..", default-features = false, features = ["server"] }
role-api = { path = "../api", features = ["server"] }
tokio = { version = "1.0", features = ["macros", "net", "rt-multi-thread", "signal"] }
tower-http = { version = "0.6", features = ["request-id", "trace"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
